Revert changes to check_cpp since it caused a lot of build issues:
```
[ 99%] Linking CXX executable ../../bin/check_cpp
/usr/bin/ld: ../../lib/libnats_static.a(cond.c.o): in function `_sub_I_00100_0':
/home/runner/work/nats.c/nats.c/src/unix/cond.c:114:(.text.startup+0xc): undefined reference to `__gcov_init'
```

or

```
+ bin/check_cpp
==3771==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```

Since the changes were not necessary (covered in the new added test)
I am reverting changes to this file.

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>